### ISSUE TITLE
Wrong version of bison

### ISSUE THREAD

**Issue by Simasjuoz** [UPPAALModelChecker/utap#25]
When running the "cmake . -B build" command, i get a "Could NOT find BISON: Found unsuitable version "3.5.1", but required is at least "3.6.0" (found /usr/bin/bison)" error

"sudo apt-get install bison" installs bison version 3.5.1

Meaning the installation guide is outdated.

**Comment by thorulf4** [comment]
We recently upgraded our development distribution to ubuntu 22, which provides more up to date packages. In which case the instructions are correct.

However ill look into updating the installation guide. As the bison version isn't actually mentioned.
